### PR TITLE
Upgrade admissionreview to v1

### PR DESCRIPTION
**Pull request by qiujian16**

### CODE REVIEW

**Comment by deads2k** [comment]
we should support both, but only advertise v1.  This will allow an orderly transition so the admission webhook configuration can change at our leisure.

**Comment by deads2k** [comment]
/lgtm

Do you happen to have a proof PR showing this in action?

**Comment by qiujian16** [comment]
this pr is for proof https://github.com/open-cluster-management/registration/pull/139. 

I copy uid from request to response here for v1 https://github.com/openshift/generic-admission-server/pull/41/files#diff-fd8ab7084521a011bc46ae5a8d595653bb6235a4102d5de2226b707264c43145R45

**Comment by deads2k** [comment]
thanks
/lgtm

**Pull request merged**
