### PR TITLE
Add restConfig in flag to support Webhook Server run locally

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

Relevant PR: https://github.com/openshift/generic-admission-server/pull/43

### CODE REVIEW

**Comment by xuezhaojun** [comment]
Hello, Stefen @sttts, this PR only contains one file modification -- the `start.go`.  Others are only vendor files we need. 
Would you like to have a review when you have time? 😁
/assign @sttts

**Comment by sttts** [comment]
I don't think we want to vendor openshift libraries here. It is a generic library, used also by project outside of OpenShift.

**Comment by xuezhaojun** [comment]
> I don't think we want to vendor openshift libraries here. It is a generic library, used also by project outside of OpenShift

Thanks for the review. @sttts 
I have changed the way to get the kubeconfig, using the standard lib instead of openshift lib.

**Pull request merged**
